apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finops

resources:
  - helmrelease.yaml

commonLabels:
  app.kubernetes.io/component: finops
  app.kubernetes.io/part-of: platform-fleet-poc
