apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
  - port: 80
    targetPort: 9898
    protocol: TCP
    name: http
